In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
%matplotlib inline

# We are creating a predictive model for NBA playoffs 2018-2019
We will be using the player data for the 2016-17 season to train our models and 2017-18 data to test our models.

In [2]:
df_tr = pd.read_csv("20162017_data.csv")
df_ts = pd.read_csv("20172018_data.csv")

In [3]:
df_tr

PLAYER TEAM  AGE  GAMES PLAYED  WINS  LOSSES  MINUTES PLAYED  \
0      DeAndre' Bembry  ATL   22            38    20      18             9.8   
1      Dennis Schroder  ATL   23            79    42      37            31.5   
2        Dwight Howard  ATL   31            74    37      37            29.7   
3       Ersan Ilyasova  ATL   30            82    35      47            26.1   
4            Gary Neal  ATL   32             2     1       1             9.2   
5        Jose Calderon  ATL   35            41    15      26            13.1   
6        Kent Bazemore  ATL   27            73    39      34            26.9   
7       Kris Humphries  ATL   32            56    31      25            12.3   
8      Lamar Patterson  ATL   25             5     1       4             8.1   
9      Malcolm Delaney  ATL   28            73    37      36            17.1   
10       Mike Dunleavy  ATL   36            53    34      19            15.9   
11        Mike Muscala  ATL   25            70    36      34            17.7   
12          Mike Scott  ATL   28            18     7      11            10.8   
13        Paul Millsap  ATL   32            69    40      29            34.0   
14          Ryan Kelly  ATL   26            16     6      10             6.9   
15      Taurean Prince  ATL   23            59    28      31            16.6   
16     Thabo Sefolosha  ATL   33            62    32      30            25.7   
17    Tim Hardaway Jr.  ATL   25            79    42      37            27.3   
18    Andrew Nicholson  BKN   27            38    20      18             9.0   
19     Anthony Bennett  BKN   24            23     3      20            11.5   
20      Archie Goodwin  BKN   22            15     8       7            14.3   
21         Brook Lopez  BKN   29            75    20      55            29.6   
22        Caris LeVert  BKN   22            57    15      42            21.7   
23     Greivis Vasquez  BKN   30             3     1       2            12.9   
24    Isaiah Whitehead  BKN   22            73    17      56            22.5   
25          Jeremy Lin  BKN   28            36    13      23            24.5   
26          Joe Harris  BKN   25            52    10      42            21.9   
27     Justin Hamilton  BKN   27            64    14      50            18.4   
28        KJ McDaniels  BKN   24            49    28      21            10.3   
29          Luis Scola  BKN   37            36     7      29            12.8   
..                 ...  ...  ...           ...   ...     ...             ...   
456         Dante Exum  UTA   21            66    40      26            18.6   
457     Derrick Favors  UTA   25            50    33      17            23.7   
458        George Hill  UTA   31            49    33      16            31.5   
459     Gordon Hayward  UTA   27            73    46      27            34.5   
460        Jeff Withey  UTA   27            51    33      18             8.5   
461         Joe Ingles  UTA   29            82    51      31            24.1   
462        Joe Johnson  UTA   36            78    47      31            23.6   
463      Joel Bolomboy  UTA   23            12     8       4             4.4   
464          Raul Neto  UTA   25            40    24      16             8.6   
465        Rodney Hood  UTA   24            59    40      19            27.0   
466        Rudy Gobert  UTA   25            81    51      30            33.9   
467       Shelvin Mack  UTA   27            55    34      21            21.9   
468         Trey Lyles  UTA   21            71    43      28            16.3   
469   Bojan Bogdanovic  WAS   28            81    23      58            25.7   
470       Bradley Beal  WAS   24            77    48      29            34.9   
471   Brandon Jennings  WAS   27            81    37      44            22.2   
472   Chris McCullough  WAS   22            16     1      15             5.0   
473      Daniel Ochefu  WAS   23            19    12       7             3.9   
474  Danuel Hous

In [4]:
one_hot_team_tr = pd.get_dummies(df_tr['TEAM'])
one_hot_team_ts = pd.get_dummies(df_ts['TEAM'])
one_hot_team_tr

ATL  BKN  BOS  CHA  CHI  CLE  DAL  DEN  DET  GSW ...   OKC  ORL  PHI  \
0      1    0    0    0    0    0    0    0    0    0 ...     0    0    0   
1      1    0    0    0    0    0    0    0    0    0 ...     0    0    0   
2      1    0    0    0    0    0    0    0    0    0 ...     0    0    0   
3      1    0    0    0    0    0    0    0    0    0 ...     0    0    0   
4      1    0    0    0    0    0    0    0    0    0 ...     0    0    0   
5      1    0    0    0    0    0    0    0    0    0 ...     0    0    0   
6      1    0    0    0    0    0    0    0    0    0 ...     0    0    0   
7      1    0    0    0    0    0    0    0    0    0 ...     0    0    0   
8      1    0    0    0    0    0    0    0    0    0 ...     0    0    0   
9      1    0    0    0    0    0    0    0    0    0 ...     0    0    0   
10     1    0    0    0    0    0    0    0    0    0 ...     0    0    0   
11     1    0    0    0    0    0    0    0    0    0 ...     0    0    0   
12     1    0    0    0    0    0    0    0    0    0 ...     0    0    0   
13     1    0    0    0    0    0    0    0    0    0 ...     0    0    0   
14     1    0    0    0    0    0    0    0    0    0 ...     0    0    0   
15     1    0    0    0    0    0    0    0    0    0 ...     0    0    0   
16     1    0    0    0    0    0    0    0    0    0 ...     0    0    0   
17     1    0    0    0    0    0    0    0    0    0 ...     0    0    0   
18     0    1    0    0    0    0    0    0    0    0 ...     0    0    0   
19     0    1    0    0    0    0    0    0    0    0 ...     0    0    0   
20     0    1    0    0    0    0    0    0    0    0 ...     0    0    0   
21     0    1    0    0    0    0    0    0    0    0 ...     0    0    0   
22     0    1    0    0    0    0    0    0    0    0 ...     0    0    0   
23     0    1    0    0    0    0    0    0    0    0 ...     0    0    0   
24     0    1    0    0    0    0    0    0    0    0 ...     0    0    0   
25     0    1    0    0    0    0    0    0    0    0 ...     0    0    0   
26     0    1    0    0    0    0    0    0    0    0 ...     0    0    0   
27     0    1    0    0    0    0    0    0    0    0 ...     0    0    0   
28     0    1    0    0    0    0    0    0    0    0 ...     0    0    0   
29     0    1    0    0    0    0    0    0    0    0 ...     0    0    0   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ... ...   ...  ...  ...   
456    0    0    0    0    0    0    0    0    0    0 ...     0    0    0   
457    0    0    0    0    0    0    0    0    0    0 ...     0    0    0   
458    0    0    0    0    0    0    0    0    0    0 ...     0    0    0   
459    0    0    0    0    0    0    0    0    0    0 ...     0    0    0   
460    0    0    0    0    0    0    0    0    0    0 ...     0    0    0   
461    0    0    0    0    0    0    0    0    0    0 ...     0    0    0   
462    0    0    0    0    0    0    0    0    0    0 ...     0    0    0   
463    0    0    0    0    0    0    0    0    0    0 ...     0    0    0   
464    0    0    0    0    0    0    0    0    0    0 ...     0    0    0   
465    0    0    0    0    0    0    0    0    0    0 ...     0    0    0   
466    0    0    0    0    0    0    0    0    0    0 ...     0    0    0   
467    0    0    0    0    0    0    0    0    0    0 ...     0    0    0   
468    0    0    0    0    0    0    0    0    0    0 ...     0    0    0   
469    0    0    0    0    0    0    0    0    0    0 ...     0    0    0   
470    0    0    0    0    0    0    0    0    0    0 ...     0    0    0   
471    0    0    0    0    0    0    0    0    0    0 ...     0    0    0   
472    0    0    0    0    0    0    0    0    0    0 ...     0    0    0   
473    0    0    0    0    0    0    0    0    0    0 ...     0    0    0   
474    0    0    0    0    0    0    0    0    0    0 ...     0    0    0   
475    0    0    0    0    0    0    0    0    0    0 ...     0    0    0   
4

In [5]:
new_df_tr=df_tr.drop(labels=['TEAM', 'PLAYER'], axis=1)
new_df_tr=one_hot_team_tr.join(new_df_tr)
new_df_ts = df_ts.drop(labels=['TEAM', 'PLAYER'], axis=1)
new_df_ts = one_hot_team_ts.join(new_df_ts)

In [6]:
new_df_ts

ATL  BKN  BOS  CHA  CHI  CLE  DAL  DEN  DET  GSW     ...       TURNOVERS  \
0      1    0    0    0    0    0    0    0    0    0     ...             0.5   
1      1    0    0    0    0    0    0    0    0    0     ...             0.4   
2      1    0    0    0    0    0    0    0    0    0     ...             0.9   
3      1    0    0    0    0    0    0    0    0    0     ...             1.8   
4      1    0    0    0    0    0    0    0    0    0     ...             2.7   
5      1    0    0    0    0    0    0    0    0    0     ...             1.4   
6      1    0    0    0    0    0    0    0    0    0     ...             1.3   
7      1    0    0    0    0    0    0    0    0    0     ...             1.0   
8      1    0    0    0    0    0    0    0    0    0     ...             1.0   
9      1    0    0    0    0    0    0    0    0    0     ...             1.4   
10     1    0    0    0    0    0    0    0    0    0     ...             0.5   
11     1    0    0    0    0    0    0    0    0    0     ...             2.4   
12     1    0    0    0    0    0    0    0    0    0     ...             1.2   
13     1    0    0    0    0    0    0    0    0    0     ...             0.8   
14     1    0    0    0    0    0    0    0    0    0     ...             1.1   
15     1    0    0    0    0    0    0    0    0    0     ...             0.0   
16     1    0    0    0    0    0    0    0    0    0     ...             2.3   
17     1    0    0    0    0    0    0    0    0    0     ...             0.3   
18     1    0    0    0    0    0    0    0    0    0     ...             0.7   
19     0    1    0    0    0    0    0    0    0    0     ...             1.0   
20     0    1    0    0    0    0    0    0    0    0     ...             2.2   
21     0    1    0    0    0    0    0    0    0    0     ...             3.1   
22     0    1    0    0    0    0    0    0    0    0     ...             0.5   
23     0    1    0    0    0    0    0    0    0    0     ...             1.4   
24     0    1    0    0    0    0    0    0    0    0     ...             1.5   
25     0    1    0    0    0    0    0    0    0    0     ...             0.0   
26     0    1    0    0    0    0    0    0    0    0     ...             0.8   
27     0    1    0    0    0    0    0    0    0    0     ...             0.4   
28     0    1    0    0    0    0    0    0    0    0     ...             1.1   
29     0    1    0    0    0    0    0    0    0    0     ...             3.0   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...     ...             ...   
510    0    0    0    0    0    0    0    0    0    0     ...             2.7   
511    0    0    0    0    0    0    0    0    0    0     ...             0.3   
512    0    0    0    0    0    0    0    0    0    0     ...             0.3   
513    0    0    0    0    0    0    0    0    0    0     ...             0.3   
514    0    0    0    0    0    0    0    0    0    0     ...             0.9   
515    0    0    0    0    0    0    0    0    0    0     ...             1.9   
516    0    0    0    0    0    0    0    0    0    0     ...             0.4   
517    0    0    0    0    0    0    0    0    0    0     ...             0.0   
518    0    0    0    0    0    0    0    0    0    0     ...             0.0   
519    0    0    0    0    0    0    0    0    0    0     ...             0.9   
520    0    0    0    0    0    0    0    0    0    0     ...             2.7   
521    0    0    0    0    0    0    0    0    0    0     ...             0.8   
522    0    0    0    0    0    0    0    0    0    0     ...             1.9   
523    0    0    0    0    0    0    0    0    0    0     ...             0.8   
524    0    0    0    0    0    0    0    0    0    0     ...             0.0   
525    0    0    0    0    0    0    0    0    0    0     ...             2.6   
526    0    0    0    0    0    0    0    0    0    0     ...             0.1   
527    0    0    0    0    0    0   

In [7]:
col_names = list(new_df_tr)
print(col_names)

['ATL', 'BKN', 'BOS', 'CHA', 'CHI', 'CLE', 'DAL', 'DEN', 'DET', 'GSW', 'HOU', 'IND', 'LAC', 'LAL', 'MEM', 'MIA', 'MIL', 'MIN', 'NOP', 'NYK', 'OKC', 'ORL', 'PHI', 'PHX', 'POR', 'SAC', 'SAS', 'TOR', 'UTA', 'WAS', 'AGE', 'GAMES PLAYED', 'WINS', 'LOSSES', 'MINUTES PLAYED', 'POINTS', 'FIELD GOALS MADE', 'FIELD GOALS ATTEMPTED', 'FIELD GOAL %', '3 POINT FIELD GOALS MADE', '3 POINT FIELD GOALS ATTEMPTED', '3 POINT FIELD GOALS %', 'FREE THROWS MADE', 'FREE THROWS ATTEMPTED', 'FREE THROW %', 'OFFENSIVE REBOUNDS', 'DEFENSIVE REBOUNDS', 'REBOUNDS', 'ASSISTS', 'TURNOVERS', 'STEALS', 'BLOCKS', 'PERSONAL FOULS', 'FANTASY POINTS', 'DOUBLE DOUBLES', 'TRIPLE DOUBLES', 'PLUS MINUS', 'PLAYOFFS', 'SEMI FINALS']


In [8]:
scaler = StandardScaler()

#this only normalizes three categories: games played, wins, losses

#new_df_tr[['GAMES PLAYED', 'WINS', 'LOSSES']]=scaler.fit_transform(new_df_tr[['GAMES PLAYED', 'WINS', 'LOSSES']])
#new_df_ts[['GAMES PLAYED', 'WINS', 'LOSSES']]=scaler.fit_transform(new_df_ts[['GAMES PLAYED', 'WINS', 'LOSSES']])

#normalizing all features
data_tr = new_df_tr.values
data_tr = np.hstack((scaler.fit_transform(data_tr[:,:data_tr.shape[1]-2]),data_tr[:,data_tr.shape[1]-2:]))
data_ts = new_df_ts.values
data_ts = np.hstack((scaler.fit_transform(data_ts[:,:data_ts.shape[1]-2]),data_ts[:,data_ts.shape[1]-2:]))

In [9]:
data_tr.shape, data_ts.shape

((486, 59), (540, 59))

In [10]:
data_tr

array([[ 5.09901951, -0.19611614, -0.17845765, ..., -0.30705464,
         1.        ,  0.        ],
       [ 5.09901951, -0.19611614, -0.17845765, ..., -0.23553365,
         1.        ,  0.        ],
       [ 5.09901951, -0.19611614, -0.17845765, ..., -0.41433614,
         1.        ,  0.        ],
       ...,
       [-0.19611614, -0.19611614, -0.17845765, ..., -0.52161763,
         1.        ,  0.        ],
       [-0.19611614, -0.19611614, -0.17845765, ...,  0.19359232,
         1.        ,  0.        ],
       [-0.19611614, -0.19611614, -0.17845765, ..., -0.87922261,
         1.        ,  0.        ]])

In [11]:
#dividing data into X and y
X_tr = np.array(data_tr[:,:data_tr.shape[1]-2])
y_tr = np.array(data_tr[:,data_tr.shape[1]-2:])
X_ts = np.array(data_ts[:,:data_ts.shape[1]-2])
y_ts = np.array(data_ts[:,data_ts.shape[1]-2:])
X_tr.shape, y_tr.shape, X_ts.shape, y_ts.shape

((486, 57), (486, 2), (540, 57), (540, 2))

In [12]:
#Model 1: Simple Logistic Regression Model (binary class, two different y values for playoffs and semi-finals)
from sklearn.linear_model import LogisticRegressionCV

#using L1 regularization
model_playoff = LogisticRegressionCV(penalty='l1',solver='liblinear')
model_semi = LogisticRegressionCV(penalty='l1',solver='liblinear')

In [13]:
y_playoff = y_tr[:,0]
y_semi = y_tr[:,1]

In [14]:
model_playoff.fit(X_tr,y_playoff)
model_semi.fit(X_tr,y_semi)

LogisticRegressionCV(Cs=10, class_weight=None, cv=None, dual=False,
           fit_intercept=True, intercept_scaling=1.0, max_iter=100,
           multi_class='ovr', n_jobs=1, penalty='l1', random_state=None,
           refit=True, scoring=None, solver='liblinear', tol=0.0001,
           verbose=0)

In [15]:
yhat_playoff = model_playoff.predict(X_ts)
model_playoff.score(X_ts, y_ts[:,0])

0.8148148148148148

In [16]:
yhat_semi = model_semi.predict(X_ts)
model_semi.score(X_ts, y_ts[:,1])

0.8685185185185185

In [17]:
model_playoff.coef_

array([[ 0.15237044, -0.08989436,  0.        , -0.23528547,  0.12815212,
         0.11333907, -0.23693091, -0.27930963, -0.21299888,  0.        ,
         0.        ,  0.11738655,  0.        , -0.11968414,  0.10677968,
        -0.27707833,  0.15305117, -0.11999107, -0.21996019, -0.10061538,
         0.05623288, -0.16607426, -0.11001562, -0.07467227,  0.11103048,
        -0.14916673,  0.        ,  0.01954696,  0.        ,  0.10457566,
         0.        ,  0.        ,  1.04618159, -0.80633746,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ]])

# The above coefficients after LASSO regularization shows that the actual player stats are wiped out and only the one-hot-encoded team names are taken into account for predicting the playoffs and semi-finals.

We will redo the fitting with a NEW data set that excludes the team name altogether and focus only on individual players' stats.

In [18]:
df_tr = pd.read_csv("20162017_data.csv")
df_ts = pd.read_csv("20172018_data.csv")

In [19]:
new_df_tr = df_tr.drop(labels=['TEAM', 'PLAYER'], axis=1)
new_df_ts = df_ts.drop(labels=['TEAM', 'PLAYER'], axis=1)

In [20]:
new_df_ts

AGE  GAMES PLAYED  WINS  LOSSES  MINUTES PLAYED  POINTS  \
0     25            15     1      14            13.9     4.6   
1     24            17     7      10             7.2     1.4   
2     25            15     4      11            27.0    10.7   
3     23            26     8      18            17.5     5.2   
4     24            67    21      46            31.0    19.4   
5     28            62    18      44            24.9    10.0   
6     23            67    18      49            17.4     6.6   
7     22             6     2       4            16.4     4.7   
8     30             1     0       1             5.4     2.0   
9     20            74    21      53            24.1    10.5   
10    28            18     3      15            12.0     2.6   
11    28            65    19      46            27.5    12.9   
12    29            54    16      38            18.8     6.3   
13    26            53    14      39            20.0     7.6   
14    29            55    19      36            16.7     4.3   
15    25             4     0       4             2.5     0.0   
16    24            82    24      58            30.0    14.1   
17    24            39    11      28            13.3     4.7   
18    22            56    15      41            17.4     7.2   
19    26            75    25      50            29.3    13.2   
20    23            71    25      46            26.2    12.1   
21    22            48    16      32            25.7    15.5   
22    31            73    34      39            21.4     5.7   
23    31            73    25      48            29.9    13.5   
24    23            16     2      14            11.2     6.3   
25    23             5     1       4             6.7     0.8   
26    22            28     7      21            12.6     6.3   
27    24            10     1       9            12.0     1.6   
28    20            72    25      47            20.0     8.2   
29    29             1     0       1            25.2    18.0   
..   ...           ...   ...     ...             ...     ...   
510   21            79    46      33            33.4    20.5   
511   31            63    36      27            12.9     2.6   
512   24             4     4       0             1.9     0.0   
513   25             9     9       0             3.5     1.0   
514   27            80    52      28            26.1     9.7   
515   30            82    48      34            31.4    11.5   
516   31            74    45      29            15.3     5.8   
517   27             5     3       2             3.8     0.4   
518   24             1     0       1             0.5     3.0   
519   26            41    28      13            12.2     4.5   
520   27            77    44      33            29.3    13.1   
521   25            69    43      26            16.7     5.0   
522   26            56    37      19            32.4    13.5   
523   34            38    16      22            21.2     8.2   
524   20             9     6       3             3.2     0.9   
525   25            82    43      39            36.3    22.6   
526   23            19    11       8             4.7     2.4   
527   23             1     0       1            13.2     2.0   
528   31            77    42      35            14.9     4.8   
529   32            33    15      18             8.6     3.4   
530   30            77    41      36            14.5     6.3   
531   27            41    23      18            34.4    19.4   
532   22            81    43      38            27.5    11.8   
533   34            82    43      39            25.3     8.4   
534   28            73    37      36            27.0    11.5   
535   29            76    39      37            18.5     8.8   
536   25            77    42      35            31.6    14.7   
537   32            28    10      18            14.0     4.9   
538   27            59    31      28            14.2     3.0   
539   26            73    39      34            22.5     7.2   

     FIELD GOALS MADE  FIELD GOALS A

In [21]:
col_names = list(new_df_tr)
print(col_names)

['AGE', 'GAMES PLAYED', 'WINS', 'LOSSES', 'MINUTES PLAYED', 'POINTS', 'FIELD GOALS MADE', 'FIELD GOALS ATTEMPTED', 'FIELD GOAL %', '3 POINT FIELD GOALS MADE', '3 POINT FIELD GOALS ATTEMPTED', '3 POINT FIELD GOALS %', 'FREE THROWS MADE', 'FREE THROWS ATTEMPTED', 'FREE THROW %', 'OFFENSIVE REBOUNDS', 'DEFENSIVE REBOUNDS', 'REBOUNDS', 'ASSISTS', 'TURNOVERS', 'STEALS', 'BLOCKS', 'PERSONAL FOULS', 'FANTASY POINTS', 'DOUBLE DOUBLES', 'TRIPLE DOUBLES', 'PLUS MINUS', 'PLAYOFFS', 'SEMI FINALS']


In [22]:
scaler = StandardScaler()

#this only normalizes three categories: games played, wins, losses

#new_df_tr[['GAMES PLAYED', 'WINS', 'LOSSES']]=scaler.fit_transform(new_df_tr[['GAMES PLAYED', 'WINS', 'LOSSES']])
#new_df_ts[['GAMES PLAYED', 'WINS', 'LOSSES']]=scaler.fit_transform(new_df_ts[['GAMES PLAYED', 'WINS', 'LOSSES']])

#normalizing all features
data_tr = new_df_tr.values
data_tr = np.hstack((scaler.fit_transform(data_tr[:,:data_tr.shape[1]-2]),data_tr[:,data_tr.shape[1]-2:]))
data_ts = new_df_ts.values
data_ts = np.hstack((scaler.fit_transform(data_ts[:,:data_ts.shape[1]-2]),data_ts[:,data_ts.shape[1]-2:]))

In [23]:
data_tr.shape, data_ts.shape

((486, 29), (540, 29))

In [24]:
data_tr

array([[-1.11403479, -0.63620822, -0.44148494, ..., -0.30705464,
         1.        ,  0.        ],
       [-0.88422965,  1.01639053,  0.97221886, ..., -0.23553365,
         1.        ,  0.        ],
       [ 0.95421146,  0.8148541 ,  0.65092254, ..., -0.41433614,
         1.        ,  0.        ],
       ...,
       [-0.65442451, -0.95866652, -0.63426273, ..., -0.52161763,
         1.        ,  0.        ],
       [-0.42461937,  0.12963022,  0.39388549, ...,  0.19359232,
         1.        ,  0.        ],
       [-0.65442451,  0.12963022,  0.52240401, ..., -0.87922261,
         1.        ,  0.        ]])

In [25]:
#dividing data into X and y
X_tr = np.array(data_tr[:,:data_tr.shape[1]-2])
y_tr = np.array(data_tr[:,data_tr.shape[1]-2:])
X_ts = np.array(data_ts[:,:data_ts.shape[1]-2])
y_ts = np.array(data_ts[:,data_ts.shape[1]-2:])
X_tr.shape, y_tr.shape, X_ts.shape, y_ts.shape

((486, 27), (486, 2), (540, 27), (540, 2))

In [63]:
#Model 1: Simple Logistic Regression Model (binary class, two different y values for playoffs and semi-finals)
from sklearn.linear_model import LogisticRegressionCV

#using Ridge regularization
model_playoff_ridge = LogisticRegressionCV(penalty='l2',solver='liblinear')
model_semi_ridge = LogisticRegressionCV(penalty='l2',solver='liblinear')

In [64]:
y_playoff = y_tr[:,0]
y_semi = y_tr[:,1]

In [65]:
model_playoff_ridge.fit(X_tr,y_playoff)
model_semi_ridge.fit(X_tr,y_semi)

LogisticRegressionCV(Cs=10, class_weight=None, cv=None, dual=False,
           fit_intercept=True, intercept_scaling=1.0, max_iter=100,
           multi_class='ovr', n_jobs=1, penalty='l2', random_state=None,
           refit=True, scoring=None, solver='liblinear', tol=0.0001,
           verbose=0)

In [66]:
yhat_playoff = model_playoff_ridge.predict(X_ts)
model_playoff_ridge.score(X_ts, y_ts[:,0])

0.8185185185185185

In [67]:
yhat_semi = model_semi_ridge.predict(X_ts)
model_semi_ridge.score(X_ts, y_ts[:,1])

0.8796296296296297

In [68]:
model_playoff_ridge.coef_

array([[ 0.08589509,  0.18880059,  1.15418403, -0.93145957, -0.05507222,
        -0.02755279, -0.04016381, -0.04151683,  0.00686956, -0.02251005,
        -0.02747373, -0.0250884 ,  0.038514  ,  0.03040962, -0.04290196,
        -0.10807946,  0.01865508, -0.02357943, -0.08409628,  0.07037499,
        -0.06279108,  0.07003496, -0.03269718, -0.04037443, -0.046655  ,
         0.07435781,  0.33073661]])

In [69]:
from sklearn.metrics import confusion_matrix as cm

playoff_matrix = cm(y_ts[:,0], yhat_playoff)
semi_matrix = cm(y_ts[:,1], yhat_semi)

In [70]:
playoff_matrix

array([[200,  59],
       [ 39, 242]], dtype=int64)

In [71]:
semi_matrix

array([[467,   0],
       [ 65,   8]], dtype=int64)

In [74]:
#using LASSO regularization
model_playoff_lasso = LogisticRegressionCV(penalty='l1',solver='liblinear')
model_semi_lasso = LogisticRegressionCV(penalty='l1',solver='liblinear')

In [75]:
model_playoff_lasso.fit(X_tr,y_playoff)
model_semi_lasso.fit(X_tr,y_semi)

LogisticRegressionCV(Cs=10, class_weight=None, cv=None, dual=False,
           fit_intercept=True, intercept_scaling=1.0, max_iter=100,
           multi_class='ovr', n_jobs=1, penalty='l1', random_state=None,
           refit=True, scoring=None, solver='liblinear', tol=0.0001,
           verbose=0)

In [76]:
yhat_playoff = model_playoff_lasso.predict(X_ts)
model_playoff_lasso.score(X_ts, y_ts[:,0])

0.837037037037037

In [77]:
yhat_semi = model_semi_lasso.predict(X_ts)
model_semi_lasso.score(X_ts, y_ts[:,1])

0.8648148148148148

In [78]:
model_playoff_lasso.coef_

array([[ 6.54685013e-02,  0.00000000e+00,  2.78000053e+00,
        -2.05432391e+00, -2.10525161e-01,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -2.09512274e-03,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00, -1.97666210e-02,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00, -5.52305629e-02,
         6.48160714e-02,  0.00000000e+00,  0.00000000e+00,
        -9.73605398e-02,  0.00000000e+00,  0.00000000e+00]])

In [79]:
playoff_matrix = cm(y_ts[:,0], yhat_playoff)
semi_matrix = cm(y_ts[:,1], yhat_semi)

In [80]:
playoff_matrix

array([[208,  51],
       [ 37, 244]], dtype=int64)

In [81]:
semi_matrix

array([[467,   0],
       [ 73,   0]], dtype=int64)

# It seems like logistic regression gives better accuracy scores than SVM, so we will make predictions on the current 2018-2019 season using logistic regression.

For playoffs, <b>LASSO regularization</b> makes more sense to use (according to both accuracy score and confusion matrix) and for semi-finals, <b>Ridge regularization</b> makes more sense to use.

Things we've tried in this model:
- one hot encoding using LASSO regularization--but it turned out to be a disaster since most features <i>besides</i> the features derived from one hot encoding were wiped out (which makes sense--but it is not what we want to see)
- Ridge Regularization on the data set that excludes the name of player and the team name
- LASSO Regularization on the data set that excludes the name of player and the team name

In [94]:
#prediction on 2018-2019 season

df = pd.read_csv("20182019_data.csv")
df

PLAYER TEAM  AGE  GAMES PLAYED  WINS  LOSSES  \
0                   Alex Len  ATL   25            23     5      18   
1             Alex Poythress  ATL   25            13     3      10   
2            Daniel Hamilton  ATL   23             2     0       2   
3            DeAndre' Bembry  ATL   24            25     5      20   
4             Dewayne Dedmon  ATL   29            19     4      15   
5               Jaylen Adams  ATL   22             4     1       3   
6                 Jeremy Lin  ATL   30            23     5      18   
7               John Collins  ATL   21            10     2       8   
8            Justin Anderson  ATL   25             8     1       7   
9              Kent Bazemore  ATL   29            25     5      20   
10             Kevin Huerter  ATL   20            24     5      19   
11             Miles Plumlee  ATL   30            16     0      16   
12            Omari Spellman  ATL   21            22     5      17   
13            Taurean Prince  ATL   24            21     5      16   
14                Trae Young  ATL   20            25     5      20   
15              Tyler Dorsey  ATL   22            12     0      12   
16              Vince Carter  ATL   41            22     3      19   
17              Allen Crabbe  BKN   26            26     9      17   
18              Caris LeVert  BKN   24            14     6       8   
19          D'Angelo Russell  BKN   22            27     9      18   
20           DeMarre Carroll  BKN   32            16     4      12   
21               Dzanan Musa  BKN   19             7     3       4   
22                  Ed Davis  BKN   29            27     9      18   
23              Jared Dudley  BKN   33            27     9      18   
24             Jarrett Allen  BKN   20            25     9      16   
25                Joe Harris  BKN   27            24     9      15   
26            Kenneth Faried  BKN   29             8     2       6   
27            Rodions Kurucs  BKN   20            10     4       6   
28   Rondae Hollis-Jefferson  BKN   23            23     7      16   
29            Shabazz Napier  BKN   27            22     6      16   
..                       ...  ...  ...           ...   ...     ...   
427           Derrick Favors  UTA   27            25    12      13   
428         Donovan Mitchell  UTA   22            22    12      10   
429                Ekpe Udoh  UTA   31            17     9       8   
430            Georges Niang  UTA   25            19    11       8   
431            Grayson Allen  UTA   23            15     6       9   
432              Jae Crowder  UTA   28            26    13      13   
433               Joe Ingles  UTA   31            26    13      13   
434              Kyle Korver  UTA   37            20     6      14   
435          Naz Mitrou-Long  UTA   25             1     0       1   
436                Raul Neto  UTA   26             9     5       4   
437              Ricky Rubio  UTA   28            26    13      13   
438            Royce O'Neale  UTA   25            26    13      13   
439              Rudy Gobert  UTA   26            26    13      13   
440          Thabo Sefolosha  UTA   34            12     4       8   
441            Austin Rivers  WAS   26            25    11      14   
442             Bradley Beal  WAS   25            25    11      14   
443           Devin Robinson  WAS   23             2     0       2   
444            Dwight Howard  WAS   33             9     4       5   
445              Ian Mahinmi  WAS   32            13     5       8   
446               Jeff Green  WAS   32            23     9      14   
447                John Wall  WAS   28            24    10      14   
448             Jordan McRae  WAS   27             4     1       3   
449          Kelly Oubre Jr.  WAS   22            25    11      14   
450          Markieff Morris  WAS   29            24    11      13   
451              Okaro White  WAS   26             2     1       1   
452          Otto Porter Jr.  WA

In [95]:
new_df = df.drop(labels=['TEAM', 'PLAYER'], axis=1)

In [96]:
data = scaler.fit_transform(new_df)
data, data.shape

(array([[-0.21474452,  0.66950969, -0.75433902, ...,  0.39617345,
         -0.13927225, -0.75900558],
        [-0.21474452, -0.59481233, -1.14320865, ..., -0.42059918,
         -0.13927225, -1.37850891],
        [-0.68769993, -1.98556656, -1.7265131 , ..., -0.42059918,
         -0.13927225, -1.09691648],
        ...,
        [-1.16065534, -0.34194793, -0.17103457, ..., -0.42059918,
         -0.13927225, -0.50557239],
        [ 0.25821088,  0.9223741 ,  0.41226988, ..., -0.42059918,
         -0.13927225,  0.05761245],
        [-1.63361075, -0.72124453, -0.94877383, ..., -0.42059918,
         -0.13927225,  0.25472715]]), (457, 27))

In [97]:
playoff_prediction = model_playoff_lasso.predict(data)
playoff_prediction

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1., 0.,
       1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1.,
       0., 1., 1., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 0., 0., 1., 1., 0., 1., 1.,
       1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 0.,
       1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1.,
       1., 0., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.

In [98]:
semi_prediction = model_semi_ridge.predict(data)
semi_prediction

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [99]:
np.sum(semi_prediction)

7.0

In [100]:
np.sum(playoff_prediction)

257.0

In [101]:
df['PLAYOFF'] = playoff_prediction.tolist()
df['SEMI-FINAL'] = semi_prediction.tolist()

In [102]:
df

PLAYER TEAM  AGE  GAMES PLAYED  WINS  LOSSES  \
0                   Alex Len  ATL   25            23     5      18   
1             Alex Poythress  ATL   25            13     3      10   
2            Daniel Hamilton  ATL   23             2     0       2   
3            DeAndre' Bembry  ATL   24            25     5      20   
4             Dewayne Dedmon  ATL   29            19     4      15   
5               Jaylen Adams  ATL   22             4     1       3   
6                 Jeremy Lin  ATL   30            23     5      18   
7               John Collins  ATL   21            10     2       8   
8            Justin Anderson  ATL   25             8     1       7   
9              Kent Bazemore  ATL   29            25     5      20   
10             Kevin Huerter  ATL   20            24     5      19   
11             Miles Plumlee  ATL   30            16     0      16   
12            Omari Spellman  ATL   21            22     5      17   
13            Taurean Prince  ATL   24            21     5      16   
14                Trae Young  ATL   20            25     5      20   
15              Tyler Dorsey  ATL   22            12     0      12   
16              Vince Carter  ATL   41            22     3      19   
17              Allen Crabbe  BKN   26            26     9      17   
18              Caris LeVert  BKN   24            14     6       8   
19          D'Angelo Russell  BKN   22            27     9      18   
20           DeMarre Carroll  BKN   32            16     4      12   
21               Dzanan Musa  BKN   19             7     3       4   
22                  Ed Davis  BKN   29            27     9      18   
23              Jared Dudley  BKN   33            27     9      18   
24             Jarrett Allen  BKN   20            25     9      16   
25                Joe Harris  BKN   27            24     9      15   
26            Kenneth Faried  BKN   29             8     2       6   
27            Rodions Kurucs  BKN   20            10     4       6   
28   Rondae Hollis-Jefferson  BKN   23            23     7      16   
29            Shabazz Napier  BKN   27            22     6      16   
..                       ...  ...  ...           ...   ...     ...   
427           Derrick Favors  UTA   27            25    12      13   
428         Donovan Mitchell  UTA   22            22    12      10   
429                Ekpe Udoh  UTA   31            17     9       8   
430            Georges Niang  UTA   25            19    11       8   
431            Grayson Allen  UTA   23            15     6       9   
432              Jae Crowder  UTA   28            26    13      13   
433               Joe Ingles  UTA   31            26    13      13   
434              Kyle Korver  UTA   37            20     6      14   
435          Naz Mitrou-Long  UTA   25             1     0       1   
436                Raul Neto  UTA   26             9     5       4   
437              Ricky Rubio  UTA   28            26    13      13   
438            Royce O'Neale  UTA   25            26    13      13   
439              Rudy Gobert  UTA   26            26    13      13   
440          Thabo Sefolosha  UTA   34            12     4       8   
441            Austin Rivers  WAS   26            25    11      14   
442             Bradley Beal  WAS   25            25    11      14   
443           Devin Robinson  WAS   23             2     0       2   
444            Dwight Howard  WAS   33             9     4       5   
445              Ian Mahinmi  WAS   32            13     5       8   
446               Jeff Green  WAS   32            23     9      14   
447                John Wall  WAS   28            24    10      14   
448             Jordan McRae  WAS   27             4     1       3   
449          Kelly Oubre Jr.  WAS   22            25    11      14   
450          Markieff Morris  WAS   29            24    11      13   
451              Okaro White  WAS   26             2     1       1   
452          Otto Porter Jr.  WA

In [104]:
csv = df.to_csv("20182019_prediction.csv")